package com.yuki.bean;

public class Starinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_starinfo.userid
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_starinfo.username
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_starinfo.gender
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_starinfo.areaname
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    private String areaname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_starinfo.fanscount
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    private Integer fanscount;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_starinfo.userid
     *
     * @return the value of tb_starinfo.userid
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_starinfo.userid
     *
     * @param userid the value for tb_starinfo.userid
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_starinfo.username
     *
     * @return the value of tb_starinfo.username
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_starinfo.username
     *
     * @param username the value for tb_starinfo.username
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_starinfo.gender
     *
     * @return the value of tb_starinfo.gender
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_starinfo.gender
     *
     * @param gender the value for tb_starinfo.gender
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_starinfo.areaname
     *
     * @return the value of tb_starinfo.areaname
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    public String getAreaname() {
        return areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_starinfo.areaname
     *
     * @param areaname the value for tb_starinfo.areaname
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    public void setAreaname(String areaname) {
        this.areaname = areaname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_starinfo.fanscount
     *
     * @return the value of tb_starinfo.fanscount
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    public Integer getFanscount() {
        return fanscount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_starinfo.fanscount
     *
     * @param fanscount the value for tb_starinfo.fanscount
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    public void setFanscount(Integer fanscount) {
        this.fanscount = fanscount;
    }
}