package com.yuki.mapper;

import com.yuki.bean.Starinfo;
import com.yuki.bean.StarinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StarinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_starinfo
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    long countByExample(StarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_starinfo
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    int deleteByExample(StarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_starinfo
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    int deleteByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_starinfo
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    int insert(Starinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_starinfo
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    int insertSelective(Starinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_starinfo
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    List<Starinfo> selectByExample(StarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_starinfo
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    Starinfo selectByPrimaryKey(String userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_starinfo
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    int updateByExampleSelective(@Param("record") Starinfo record, @Param("example") StarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_starinfo
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    int updateByExample(@Param("record") Starinfo record, @Param("example") StarinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_starinfo
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    int updateByPrimaryKeySelective(Starinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_starinfo
     *
     * @mbg.generated Mon May 24 15:01:11 CST 2021
     */
    int updateByPrimaryKey(Starinfo record);
}